#! /bin/sh

xsetroot -cursor_name left_ptr &
xset m 0 0 &
nitrogen --restore &
xinput --set-prop 8 'Coordinate Transformation Matrix' 0.5 0 0 0 0.5 0 0 0 1 &
sxhkd &

bspc monitor HDMI-1 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true 
